events {
    worker_connections 1024;
}

http {
    upstream fastapi_workers {
        least_conn;
        server app1:8000;
        server app2:8000;
        server app3:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://fastapi_workers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /nginx_status {
            stub_status on;
            allow all;
        }
    }
}
